server:
  port: 8080
spring:
  application:
    name: dudu
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dudu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql
    druid:
      test-while-idle: false
  # 包含其他中间件相关配置文件
  profiles:
    include:
      - redis
      - rabbitmq

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jiw.dudu.entities